name: "Publish Module"
description: "Publishes a specific module to GitHub Packages"
inputs:
  module:
    description: "The module to publish"
    required: true
  github-token:
    description: "GitHub Token to authenticate"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set executable permissions
      shell: bash
      run: chmod +x ./entrypoint.sh

    - name: Run Publish Script
      run: ./entrypoint.sh
      shell: bash
      env:
        MODULE_NAME: ${{ inputs.module }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
