name: "Publish Module"
description: "Publishes a specific module to GitHub Packages"
inputs:
  module:
    description: "The module to publish"
    required: true
  git-token:
    description: "GitHub Token to authenticate"
    required: true

runs:
  using: "composite"
  steps:
    - name: Publish module
      shell: bash
      run: ./gradlew :${{ inputs.module }}:publish
      env:
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ inputs.git-token }}
