name: 'Run build'
description: 'Compile project'

inputs:
  module:
    description: 'Module to build'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Set executable permissions
      shell: bash
      run: |
        ls -a
        chmod +x ./entrypoint.sh

    - name: Run Build Script
      run: ./entrypoint.sh
      shell: bash
      env:
        REPO_NAME: ${{ inputs.repo }}