name: 'Bump version'
description: 'Bump version'

inputs:
  module:
    description: 'module to bump version'
    required: true
  release-type:
    description: 'minor|major|patch'
    required: false
    default: 'patch'

runs:
  using: composite
  steps:
    - name: Run Version Bump
      shell: bash
      run: ./gradlew bumpVersion -Pmodule=${{ inputs.module }} -PreleaseType=${{ inputs.release-type }}

    - name: Commit and Push Version Bump
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add gradle.properties
        git commit -am "🔖 Bump version for ${{ inputs.module }}"
        git push

    - name: log status
      shell: bash
      run: echo "✅ Version bumped successfully"
