name: 'Bump version'
description: 'Bump version'

inputs:
  module:
    description: 'module to bump version'
    required: true
  release-type:
    description: 'minor|major|patch'
    required: false
    default: 'patch'
  github-token:
    description: 'gh PAT'
    required: true

runs:
  using: composite
  steps:
    - name: Set executable permissions
      shell: bash
      run: chmod +x .github/actions/bump_version/entrypoint.sh

    - name: Bump version
      run: .github/actions/bump_version/entrypoint.sh
      shell: bash
      env:
        MODULE_NAME: ${{ inputs.module }}
        RELEASE_TYPE: ${{ inputs.release-type }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
