on:
  push:
    branches:
      - main
    paths:
      - positions-rpc/**

env:
  MODULE: positions-rpc

jobs:
  bump-version:
    runs-on: ubuntu-latest
    concurrency:
      group: bump-version-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: build
        uses: yareee-project/build-action@main
        with:
          module: ${{ env.MODULE }}

      - name: bump version
        uses: yaree-project/bump_version@main
        with:
          module: ${{ env.MODULE }}
          release-type: "patch"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: bump-version

    steps:
      - name: build
        uses: yareee-project/build-action@main
        with:
          module: ${{ env.MODULE }}

      - name: publish
        uses: yaree-project/publish@main
        with:
          module: ${{ env.MODULE }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
