name: Publish Modules

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Build Project
        run: ./gradlew build

      - name: Get modified modules
        id: modified-modules
        run: |
          git fetch origin main
          MODIFIED_MODULES=$(git diff --name-only origin/main | grep 'build.gradle' | sed 's|/build.gradle||' | sort -u)
          echo "::set-output name=modules::${MODIFIED_MODULES}"

      - name: Bump Version and Publish Modules
        run: |
          for MODULE in ${{ steps.modified-modules.outputs.modules }}; do
            echo "Processing module: $MODULE"
            ./gradlew :$MODULE:bumpVersion -Pmodule=$MODULE -PreleaseType=patch
            git config --global user.email "github-actions@github.com"
            git config --global user.name "GitHub Actions"
            git add gradle.properties
            git commit -m "Bump version for $MODULE"
            ./gradlew :$MODULE:publish
          done

      - name: Bump BOM Version and Publish
        run: |
          ./gradlew :common-rpc-bom:bumpVersion -PreleaseType=patch
          git add gradle.properties
          git commit -m "Bump BOM version"
          ./gradlew :common-rpc-bom:publish
